# -*- coding: utf-8 -*-
"""voice-recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v_UYOnAusIgimt4qaGMmq0-BXso6n8P4
"""

!pip install SpeechRecognition

import urllib.request

# download test audio file and save as test.wav
urllib.request.urlretrieve("http://www.fit.vutbr.cz/~motlicek/sympatex/f2bjrop1.0.wav", "test.wav")

import speech_recognition as sr

# Initialize the recognizer class used for speech recognition
r = sr.Recognizer()

# Read the audio file we downloaded as audio_source
with sr.AudioFile("test.wav") as audio_source:
  
  # listen to the audio file and store in text_audio variable
  text_audio = r.listen(audio_source)

# handle any error that may occur if the recognize_google() method does not work
  try:

    # we are using google's speech recognition
    print("Converting audio to text, please wait...")
    output = r.recognize_google(text_audio)
    print(f"Result: \n{output}")
  except:
    print("Could not process request")

!pip install gTTS

# text to speech

from gtts import gTTS
  
# This module is imported so that we can 
# play the converted audio
import os

# get output from previous speech to text module
mytext = output
  
# Language in which you want to convert
language = 'en'
  
# Passing the text and language to the engine, 
# here we have marked slow=False. Which tells 
# the module that the converted audio should 
# have a high speed
myobj = gTTS(text=mytext, lang=language, slow=False)
  
# Saving the converted audio in a mp3 file named
# welcome 
myobj.save("speech_output.mp3")
  
# Playing the converted file
os.system("mpg321 speech_output.mp3")

!pip install chatterbot
# Import "chatbot" from 

# chatterbot package.

from chatterbot import ChatBot

  

# Inorder to train our bot, we have 

# to import a trainer package

# "ChatterBotCorpusTrainer"

from chatterbot.trainers import ChatterBotCorpusTrainer

 



# Give a name to the chatbot “corona bot”

# and assign a trainer component.

chatbot=ChatBot('corona bot')

 

# Create a new trainer for the chatbot

trainer = ChatterBotCorpusTrainer(chatbot)

  

# Now let us train our bot with multiple corpus

trainer.train("chatterbot.corpus.english.greetings",

              "chatterbot.corpus.english.conversations" )

  

response = chatbot.get_response('What is your Number')

print(response)

 

response = chatbot.get_response('Who are you?')

print(response)
